### ISSUE TITLE
Does progressively support img srcset's

### ISSUE THREAD

**Issue by sphism** [thinker3197/progressively#1]
Just wondering if progressively supports img srcset's, or html5 picture element with a list of sources.

Looks like a great little library.

**Comment by thinker3197** [comment]
@sphism I will try to extend support for `img srcset` attribute within a few days.

**Comment by sphism** [comment]
Oh wow. That would be great. I used the picture element on a recent project and it's amazing but in hindsight I think it was overkill and img src sets seem to be the recommended approach.

Would be neat if you could just add a tiny image to the srcset and progressively picked that up as the initial image ???

**Comment by thinker3197** [comment]
I'll try to make the suggested enhancements. Will have to make sure that this is a much used feature and would be helpful to add. Thanks for you suggestions @sphism. 
Closing issue now.

**Comment by jitendersandhu** [comment]
@thinker3197 Any updates on support for picture element? Is this already added as a feature in recent releases?

**Comment by thinker3197** [comment]
The `<picture>` is currently an experimental feature. At the moment, **progressively** doesn't aim to add any features that are experimental and has limited browser support.
ref:  https://developer.mozilla.org/en/docs/Web/HTML/Element/picture
