### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by mshakour** [thinker3197/progressively#10]
Hello!
Thanks for the great light-weight code @thinker3197 !

I tried the library and it works like a charm, the only problem when i try to use it with a responsive image, i find myself obligated to specify `height` for the `figure`. when i try `height: auto `the image disappear.
any advice? 

Thanks!

**Comment by thinker3197** [comment]
@mshakour thanks for pointing this. This is now fixed with [this](https://github.com/thinker3197/progressively/commit/1efc99aed077b7507067eda1881be3b84ee87439) commit.
Update your `package.json` now or use the new files from `/dist`.
