### ISSUE TITLE
Add support for creating smaller image version

### ISSUE THREAD

**Issue by thinker3197** [thinker3197/progressively#13]
Create a `grunt` plugin or `npm` script that can be integrated to tooling and auto creates smaller versions of images so that user's don't have to do that manually

**Comment by thiamsantos** [comment]
Could be made another package, a small cli utility to do this. And mention it on `Readme`.

**Comment by thiamsantos** [comment]
I'm working on a tool to do this. I called it [lowly](https://github.com/thiamsantos/lowly). What do you think about it @thinker3197?

For now it takes an image and creates a version of that image with 30px of width and a height that preserves the aspect ratio, resulting in really small images under 1KB.

**Comment by thinker3197** [comment]
@thiamsantos Great job there! Can you reference this in `progressively's` README and also explain the usage in brief? 
Further plans - We should export `lowly` as a grunt and gulp plugin (easy task), for people to seamlessly integrate them in their build tooling.

**Comment by the94air** [comment]
what is the best size for the smaller image (lets say I have a banner image in `1366*600` size)?

**Comment by thinker3197** [comment]
The pixel size doesn't matters, file size does. So, anything less than 1kb is good!

**Comment by the94air** [comment]
Great, Thanks :+1:
