### ISSUE TITLE
Remove demo.gif from master branch

### ISSUE THREAD

**Issue by CodeBrauer** [thinker3197/progressively#29]
The gif is 3MB large, and will be loaded anytime the package will be added with yarn/bower etc.

We don't need this gif as users or developers, so this asset could be hosted with [github pages](https://help.github.com/articles/what-is-github-pages/) or using the [Github CDN Issue trick](https://stackoverflow.com/a/20959426/1990745)

**Comment by thiamsantos** [comment]
Well noted @CodeBrauer, but there is no need to remove the gif from the master branch. If you don't want a file to be published on npm just include a [files field on `package.json`](https://docs.npmjs.com/files/package.json#files) or include a [`npmignore`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) on the project.

**Comment by CodeBrauer** [comment]
Yeah but still, if I just add this package it will be downloaded. If every project had some gif files, my vendor folders in every project would be tremendous.
