### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by PascalPixel** [thinker3197/progressively#8]
rails-assets.org is not showing this repo even though it's on bower, I think it's because there is no Release on Github?

**Comment by thinker3197** [comment]
Not sure why that's happening. I'm planing to do a release for `v2.0.0` soon. 
Do you have a suggestion to fix this @PascalPixel?

**Comment by PascalPixel** [comment]
Aye can confirm it's because there is no Release on Github, can you make a v1.0.0 release here? 👍

**Comment by PascalPixel** [comment]
Here: https://github.com/thinker3197/progressively/releases 🌈

**Comment by thinker3197** [comment]
@PascalPixel I've published the release. Can you please check if the issue is solved?

Thanks!

**Comment by PascalPixel** [comment]
It works now! Thank you @thinker3197
