### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by thiamsantos** [thinker3197/progressively#9]
First of, I'd like to say how awesome this project is. @thinker3197 thanks for publishing it :tada:.
But, I have some suggestions that might improve the quality of the project.

### Implement tests
Would be good to implement unit tests, and take that opportunity to separate the codebase into small modules (maybe using the [ES6 modules syntax](http://www.2ality.com/2014/09/es6-modules-final.html)).

### Code style
Follow a popular and battle tested code style like [xo](https://github.com/sindresorhus/xo), [standard](http://standardjs.com/) or [Airbnb](https://github.com/airbnb/javascript). I personally prefer xo but they all are good options.

### Readme
Would be great update the readme following the [standard readme](https://github.com/richardlitt/standard-readme) [specification](https://github.com/RichardLitt/standard-readme/blob/master/spec.md) in order to provide a predictable format, helping the people to understand the purpose of the project and how to use it.

### Contributing guidelines
Improve the [present guidelines](https://github.com/thinker3197/progressively#contributing), maybe making something like [this example](https://github.com/developit/mitt#contribute).

### Ignore files
Use some [approach](https://github.com/npm/npm/wiki/Files-and-Ignores) for npm ignore some files when publishing the package.

What do you think?
For anyone of these ideas I would be happy on send a Pull Request :smile:

**Comment by thinker3197** [comment]
Hey @thiamsantos, thanks for these suggestions. I'm currently a bit busy due to my professional work that's why couldn't dedicate much time to this project at the moment. I'll soon be free, and planning to roll out `v2.0.0`. 
For the above suggestions, feel free to send a pr, if that improves the project in any way.
I really appreciate your efforts. 
Thanks!

**Comment by thiamsantos** [comment]
Thanks for the quick response @thinker3197

> For the above suggestions, feel free to send a pr, if that improves the project in any way.

I will send it soon, but I just need some things from you.

- Could you activate this repo on [Travis CI](https://travis-ci.org/) and on [Coveralls](https://coveralls.io/) too? Just to add some [cool badges](http://shields.io/) on README.
- Do you prefer to use for indentation tabs or 2 spaces?
- Do you prefer to use or not to use semicolons on javascript code?
